### ISSUE TITLE
Is there a way to filter logs origin?

### ISSUE THREAD

**Issue by paulrouget** [Nercury/android_logger-rs#13]
My project use multiple crates. I only want the logs from mine, not all the others.

**Comment by Nercury** [comment]
No, there isn't. But the logcat can filter the logs too, right?

**Comment by paulrouget** [comment]
You're right, but in my case, the amount of log is pretty gigantic (using it for Servo). logcat ends up chocking on this, even with filtering. I guess the logcat buffer gets filled too fast.

**Comment by Nercury** [comment]
Well i think it is reasonable to add this feature. Do you want to work on this?
