### ISSUE TITLE
Panic messages are not printed on android.

### ISSUE THREAD

**Issue by faisal00813** [Nercury/android_logger-rs#20]
I have android logger setup in the rust library. 
If the library panics, there are no errors logged. Messages are only logged if the explicit info!() or error!() is called.

**Comment by Dushistov** [comment]
@faisal00813, do you use [log-panics crate](https://crates.io/crates/log-panics) in additon to android-logger crate? Because of without it your library does not use log infrastructure and just print to stdout/stderr, this is how rust stdlib works.

**Comment by faisal00813** [comment]
@Dushistov Thanks!
That helped. But the log message does not have the line number.
I think passing RUST_BACKTRACE should do that. Do you know how to pass env variables to the Android app through android studio?

**Comment by Dushistov** [comment]
@faisal00813,  you can use `libc::setenv` in place where you initialize android logger and log-panics.
But I, personally, never use it, because of android runtime print backtrace of crashed code (native and java) to log. May be you just build without debug info?

**Comment by Nercury** [comment]
Hey, thanks for bug report. The panic handling won't be in scope of this library. However, it is easy to create your own panic handler: [the code in log-panics crate is not compex](https://github.com/sfackler/rust-log-panics/blob/master/src/lib.rs).
