### ISSUE TITLE
Don't use `::` as a module separator

### ISSUE THREAD

**Issue by paulrouget** [Nercury/android_logger-rs#22]
That's pretty annoying, but Android tag names are not supposed to include columns apparently.

With `adb logcat`, we can not filter by module if the module include a column.

For `foo::bar`, we can't do `adb logcat foo::bar` because `adb` will interpret that as "tag foo, log level bar".

I'm not sure what should be done here. Maybe replace `::` with `;;`, then we could do: `adb logcat foo;;bar`.

**Comment by paulrouget** [comment]
Or use a generic tag (`Rust`) and add the module name to the log.

**Comment by Nercury** [comment]
`Rust` name seems reasonable. Tags also have a character limit, and that would be another reason to avoid module names in tags.

**Comment by paulrouget** [comment]
Would you recommend to just use `Rust` as a tag and the log message, or `Rust` as a tag and the module name + the log message?

For our use case (Servo), we don't need to module name.

**Comment by Nercury** [comment]
It would be nice to have module name in the message. But I am currently not using this library (android project got delayed), so it would be better for you to decide.
