### ISSUE TITLE
RFC: may be use std::sync::Once instead of std::sync::RwLock ?

### ISSUE THREAD

**Issue by Dushistov** [Nercury/android_logger-rs#24]
Number of `RwLock` were increased after #23 
```Rust
filter: RwLock<Filter>,
tag: RwLock<Option<CString>>,
```
may be use `std::sync::Once` instead? It looks like
much simplier (one atomic) in compare to `RwLock` which implementation depend on OS,
in case of android I suppose it uses `pthread_rwlock_t` which is not light weight.

What do you think?

**Comment by Nercury** [comment]
Interesting, it's the first time I hear about `std::sync::Once`. Looks like a reasonable thing to do.
Also `filter` and `tag` could probably be grouped into a single structure with one lock.

**Comment by Nercury** [comment]
https://github.com/Nercury/android_logger-rs/pull/31 improved the situation by combining filter and tag under one config.
