### ISSUE TITLE
Enhance module path match in filter

### ISSUE THREAD

**Issue by burmecia** [Nercury/android_logger-rs#28]
Is that possible to use `str.contains` to do module path match in filter, just like env_logger did? The use case is when there are many crates and modules could output logs, it is easier to use string pattern match to filter out it.

**Comment by Nercury** [comment]
These changes are welcome. Although it would also be great to do some general maintenance for this library before adding new features. From the top of my head: things could be separated into different files, the amount of unsafe code could probably be reduced, and line-splitting algorithm could be rewritten into more idiomatic Rust.
