### ISSUE TITLE
Allow for multiple log level depending on the module

### ISSUE THREAD

**Issue by fredszaq** [Nercury/android_logger-rs#30]
Hi!

I'm in the case where I want to have a different log level depending on the crate emitting the log. The current API allows only for a single level and an additional white list.

### Proposed new api
add a `with_module_path_level` to the filter to specify the different modules you want to be treated differently from the default. As a side note the behaviour in #29 would be interesting here too

**Comment by Nercury** [comment]
Sure, go ahead and try it out!

**Comment by Nercury** [comment]
Resolved!
