### ISSUE TITLE
Setting levels for multiple crates does not function?

### ISSUE THREAD

**Issue by tbraun96** [Nercury/android_logger-rs#36]
```
// Show trace and above level messages for this crate and some_other_crate
    android_logger::init_once(
        Config::default().with_min_level(Level::Trace).with_filter(FilterBuilder::default()
            .parse("trace,some_other_crate=trace").build()))
```

First, I want to make sure the syntax above is correct. Whereas the primary crate displays logs correctly, ``some_other_crate`` doesn't show anything at all. Just incase, in ``some_other_crate``, I have this in ``Cargo.toml``:

```
log = { version = "0.4.8", features = ["std", "max_level_trace", "release_max_level_trace"] }
```

I'm including the aforementioned line because I don't know if that may cause interference or not

**Comment by Nercury** [comment]
I have no idea how it works, because this feature was submitted by a contributor.
