### ISSUE TITLE
How to link to android log lib?

### ISSUE THREAD

**Issue by fzyzcjy** [Nercury/android_logger-rs#44]
Hi, 

> This only works on Android and requires linking to log which is only available under android.

But how can I linking to the log? Thanks!

**Comment by stan-irl** [comment]
@Nercury is this still the case? Im trying to integrate this logger into an existing cross platform library but im getting `Undefined __android_log_write` when I load my `.so` file. 

I'm building with [rust-android-gradle](https://github.com/mozilla/rust-android-gradle#prebuilttoolchains) and using the default toolchain.

**Comment by stan-irl** [comment]
please ignore my previous comment. I did a fresh build and its working just fine. thanks so much - this library extremely helpful
