### ISSUE TITLE
Consider implementing `Log::enabled`

### ISSUE THREAD

**Issue by bnjbvr** [Nercury/android_logger-rs#45]
I was curious if there was a particular reason why `Log::enabled` was implemented to return `true` all the time: was it because it was never really implemented historically, or because it would entail taking the global lock more often? I think it would be nice to implement because `log`'s `log_enabled!()` macro relies on this to decide whether to enter a code section or not, and this can have a pretty large performance impact, so it would be nice to have. If there's interest and no particular reason why it was not implemented, I'd be happy to write the simplest patch: take lock, compare config filters with what's in the metadata.

**Comment by Nercury** [comment]
I don't remember - it could also be because I misunderstood the API. I think the lock overhead should not be an issue (and it can be even more optimized with an atomic if needed).
