### ISSUE TITLE
Support selecting the target log buffer

### ISSUE THREAD

**Issue by randomPoison** [Nercury/android_logger-rs#49]
Android has [several different log buffers](https://developer.android.com/ndk/reference/group/logging#group___logging_1gabcd142e91968af61158b3d0b72eb72df) that can be targeted when writing a log message. This library currently only supports writing to the main buffer, but it would be useful to select different target buffers in some cases. In the Android codebase [we're currently patching android_logger](https://cs.android.com/android/platform/superproject/+/master:external/rust/crates/android_logger/patches/0001-Support-selecting-target-log-buffer.patch;drc=c6a999020b54e2106d756bc2a73741b6a1d319f3) so that we can select a target buffer from Rust code, but it would be nice to add this support in the main crate so that others can take advantage of it (and so that it's easier for us to pull in future updates of android_logger).

I'll open up a PR that pulls in our existing patches shortly, but I wanted to also open this separate issue in case there were any comments/concerns with adding this feature 🙂

**Comment by Nercury** [comment]
No concerns, it's the logger for android and we can add new functionality. Sorry for being late to respond to this. I will review this shortly.

**Comment by Nercury** [comment]
I have released update with no breaking changes, this will require version change to `0.12` since there seems to be a lot of crate users.

**Comment by Nercury** [comment]
See https://github.com/Nercury/android_logger-rs/pull/64
