### ISSUE TITLE
Crate compilation broken on Android

### ISSUE THREAD

**Issue by vivienm** [Nercury/android_logger-rs#58]
Hello,

I've not been able to compile the latest release (0.11.2) of this crate on Android. Compilation fails with the following output:

```
   Compiling android_logger v0.11.2
error[E0061]: this function takes 2 arguments but 1 argument was supplied
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/android_logger-0.11.2/src/lib.rs:295:9
    |
295 |           Self::new_with_priority(match level {
    |  _________^^^^^^^^^^^^^^^^^^^^^^^-
296 | |             Level::Warn => LogPriority::WARN,
297 | |             Level::Info => LogPriority::INFO,
298 | |             Level::Debug => LogPriority::DEBUG,
299 | |             Level::Error => LogPriority::ERROR,
300 | |             Level::Trace => LogPriority::VERBOSE,
301 | |         })
    | |__________- an argument of type `&CStr` is missing
    |
note: associated function defined here
   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/android_logger-0.11.2/src/lib.rs:282:12
    |
282 |     pub fn new_with_priority(priority: log_ffi::LogPriority, tag: &CStr) -> PlatformLogWriter {
    |            ^^^^^^^^^^^^^^^^^ ------------------------------  ----------
help: provide the argument
    |
295 ~         Self::new_with_priority(match level {
296 +             Level::Warn => LogPriority::WARN,
297 +             Level::Info => LogPriority::INFO,
298 +             Level::Debug => LogPriority::DEBUG,
299 +             Level::Error => LogPriority::ERROR,
300 +             Level::Trace => LogPriority::VERBOSE,
301 +         }, /* &CStr */)
    |
```

As specified in the output, it looks like function `new` doesn't pass the mandatory `tag` argument to `new_with_priority`: https://github.com/Nercury/android_logger-rs/blob/38186ece1056d90b8f75fd2a5eb5c860e0a1704e/src/lib.rs#L281-L302

**Comment by tyranron** [comment]
I have the same issue.

Seems to be regressed in https://github.com/Nercury/android_logger-rs/commit/ec1262eee4c3cf3e1d7edd2250e9c7c6cbd142fb.

Wasn't caught by CI because of `#[cfg(target_os = "android")]`. Despite CI installs targets, it doesn't specify it to the `cargo` commands via `--target=${{ matrix.target }}`  flag: https://github.com/Nercury/android_logger-rs/blob/959f90a939a48978278ceec0f4cfd41b68c3972e/.github/workflows/ci.yml#L38-L53

**Comment by Ludea** [comment]
get same issue

**Comment by tyranron** [comment]
@vivienm @Ludea @MarijnS95 @bryanmehall @danielgranhao @charroch @mockersf @alice-i-cecile

Released in [0.11.3](https://crates.io/crates/android_logger/0.11.3). The [broken 0.11.2](https://crates.io/crates/android_logger/0.11.2) has been yanked.

**Comment by mockersf** [comment]
thanks!

**Comment by MarijnS95** [comment]
Cool, thanks! It's always a bit unfortunate when a crate targeting a said platform doesn't build on said platform, but it looks like the CI mishap has been addressed too :tada:
